# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.hostname = "docker-host"
  config.vm.provision "docker"
  
  config.vm.box = "ubuntu/trusty64"
  
  config.vm.provision :shell, inline: "/bin/bash /app/docker-scripts/run_docker_containers.sh", run: 'always'

  config.vm.synced_folder "../", "/app"
  config.vm.synced_folder "~/.m2", "/home/vagrant/.m2"

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
    config.cache.synced_folder_opts = {
      mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
    }
  end
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
  end
end
